#!/bin/bash
# Example: ./cpb original_file destination_file
# Thanks to homey for the script.
usage()
{
   echo -e "cp with progress bar\n"
   echo -e "Usage: $0 original_file destination_file\n"
   echo -e "BOTH MUST BE FILE!\nThanks to homey for the script.\n"
   exit 1;
}

tput civis -- invisible
test $# == 2 || usage
orig_size=$(stat -c %s $1)

>$2
dest_size=0
cp -f $1 $2 &

while [ $orig_size -gt $dest_size ] ; do
   dest_size=$(stat -c %s $2)
   pct=$((( 69 * $dest_size ) / $orig_size ))

    echo -en "\r["
    for j in `seq 1 $pct`; do
        echo -n "="
    done
    echo -n ">"
    for j in `seq $pct 68`; do
        echo -n "."
    done
    echo -n "] "
    echo -n $((( 100 * $pct ) / 69 ))
    echo -n "%"
done
echo
tput cnorm -- normal
